"""Curated registrable-domain → Shallalist domain_type seed map + light heuristics.

Keys must be eTLD+1（与 ``registrable_from`` / DomainProfile.domain 一致）。
子域（如 baike.baidu.com）会归一到根域，无法单独打标。
"""

from __future__ import annotations

# eTLD+1 → Shallalist code（偏国内引用信源，兼顾常见全球站）
DOMAIN_TYPE_SEEDS: dict[str, str] = {
    # ── social / UGC ──────────────────────────────────────────────
    "zhihu.com": "socialnet",
    "weibo.com": "socialnet",
    "weibo.cn": "socialnet",
    "xiaohongshu.com": "socialnet",
    "douban.com": "socialnet",
    "jianshu.com": "socialnet",
    "lofter.com": "socialnet",
    "toutiao.com": "socialnet",
    "ixigua.com": "socialnet",
    "kuaishou.com": "socialnet",
    "kwai.com": "socialnet",
    "qq.com": "socialnet",  # 含微信公众号 mp.weixin.qq.com 等
    "facebook.com": "socialnet",
    "twitter.com": "socialnet",
    "x.com": "socialnet",
    "linkedin.com": "socialnet",
    "instagram.com": "socialnet",
    "threads.net": "socialnet",
    "pinterest.com": "socialnet",
    "tumblr.com": "socialnet",
    "snapchat.com": "socialnet",
    "whatsapp.com": "socialnet",
    "telegram.org": "socialnet",
    "quora.com": "socialnet",
    "substack.com": "socialnet",
    "producthunt.com": "socialnet",
    "mastodon.social": "socialnet",
    "blogspot.com": "socialnet",
    "wordpress.com": "socialnet",
    "wordpress.org": "forum",
    "fandom.com": "socialnet",
    "line.me": "socialnet",
    "naver.com": "socialnet",
    "daum.net": "socialnet",
    # ── forum / 技术与兴趣社区 ────────────────────────────────────
    "reddit.com": "forum",
    "discord.com": "forum",
    "stackoverflow.com": "forum",
    "stackexchange.com": "forum",
    "dev.to": "forum",
    "hashnode.com": "forum",
    "ycombinator.com": "forum",
    "lobste.rs": "forum",
    "indiehackers.com": "forum",
    "csdn.net": "forum",
    "cnblogs.com": "forum",
    "oschina.net": "forum",
    "juejin.cn": "forum",
    "segmentfault.com": "forum",
    "v2ex.com": "forum",
    "ithome.com": "forum",
    "52pojie.cn": "forum",
    "chiphell.com": "forum",
    "nga.cn": "forum",
    "ngabbs.com": "forum",
    "hupu.com": "forum",
    "taptap.cn": "forum",
    "taptap.com": "forum",
    "miui.com": "forum",
    "gitee.com": "forum",
    "gitcode.com": "forum",
    "aliyun.com": "forum",
    "tencentcloud.com": "forum",
    "huaweicloud.com": "forum",
    "nowcoder.com": "forum",
    "leetcode.cn": "forum",
    "luogu.com.cn": "forum",
    "woshipm.com": "forum",
    "pmcaff.com": "forum",
    "infoq.cn": "forum",
    "zcool.com.cn": "hobby",
    "ui.cn": "hobby",
    # ── video / recreation / movies / music / 直播 / 阅读 ──────────
    "bilibili.com": "recreation",
    "b23.tv": "recreation",
    "acfun.cn": "recreation",
    "youtube.com": "recreation",
    "youtu.be": "recreation",
    "tiktok.com": "recreation",
    "twitch.tv": "recreation",
    "vimeo.com": "recreation",
    "netflix.com": "movies",
    "hulu.com": "movies",
    "disney.com": "movies",
    "disneyplus.com": "movies",
    "imdb.com": "movies",
    "rottentomatoes.com": "movies",
    "spotify.com": "music",
    "soundcloud.com": "music",
    "pitchfork.com": "music",
    "rollingstone.com": "music",
    "espn.com": "recreation",
    "nba.com": "recreation",
    "fifa.com": "recreation",
    "uefa.com": "recreation",
    "douyin.com": "recreation",
    "huya.com": "recreation",
    "douyu.com": "recreation",
    "yy.com": "recreation",
    "inke.cn": "recreation",
    "huajiao.com": "recreation",
    "iqiyi.com": "movies",
    "youku.com": "movies",
    "mgtv.com": "movies",
    "pptv.com": "movies",
    "le.com": "movies",
    "1905.com": "movies",
    "miguvideo.com": "movies",
    "kugou.com": "music",
    "kuwo.cn": "music",
    "ximalaya.com": "music",
    "qingting.fm": "music",
    "lizhi.fm": "music",
    "qidian.com": "recreation",
    "zongheng.com": "recreation",
    "jjwxc.net": "recreation",
    "fanqienovel.com": "recreation",
    "changdunovel.com": "recreation",
    "dmzj.com": "recreation",
    "manhuagui.com": "recreation",
    "zhibo8.cc": "recreation",
    "dongqiudi.com": "recreation",
    # ── news / media / 门户与科技媒体 ─────────────────────────────
    "36kr.com": "news",
    "huxiu.com": "news",
    "thepaper.cn": "news",
    "sina.com.cn": "news",
    "sina.cn": "news",
    "sohu.com": "news",
    "163.com": "news",
    "ifeng.com": "news",
    "cctv.com": "news",
    "cntv.cn": "news",
    "people.com.cn": "news",
    "xinhuanet.com": "news",
    "chinadaily.com.cn": "news",
    "gmw.cn": "news",
    "youth.cn": "news",
    "chinanews.com.cn": "news",
    "chinanews.com": "news",
    "cri.cn": "news",
    "cankaoxiaoxi.com": "news",
    "guancha.cn": "news",
    "huanqiu.com": "news",
    "china.com": "news",
    "china.com.cn": "news",
    "ce.cn": "news",
    "guokr.com": "news",
    "caixin.com": "news",
    "jiemian.com": "news",
    "yicai.com": "news",
    "cls.cn": "news",
    "nbd.com.cn": "news",
    "eeo.com.cn": "news",
    "21jingji.com": "news",
    "infzm.com": "news",
    "bjnews.com.cn": "news",
    "theinitium.com": "news",
    "zaobao.com": "news",
    "zaobao.com.sg": "news",
    "ftchinese.com": "news",
    "sspai.com": "news",
    "pingwest.com": "news",
    "leiphone.com": "news",
    "geekpark.net": "news",
    "tmtpost.com": "news",
    "iyiou.com": "news",
    "ebrun.com": "news",
    "cyzone.cn": "news",
    "lieyunwang.com": "news",
    "donews.com": "news",
    "techweb.com.cn": "news",
    "cnbeta.com": "news",
    "cnbeta.com.tw": "news",
    "solidot.org": "news",
    "landiannews.com": "news",
    "mydrivers.com": "news",
    "zol.com.cn": "news",
    "pconline.com.cn": "news",
    "yesky.com": "news",
    "medium.com": "news",
    "cnn.com": "news",
    "bbc.com": "news",
    "bbc.co.uk": "news",
    "nytimes.com": "news",
    "reuters.com": "news",
    "apnews.com": "news",
    "wsj.com": "news",
    "washingtonpost.com": "news",
    "theguardian.com": "news",
    "economist.com": "news",
    "ft.com": "news",
    "forbes.com": "news",
    "businessinsider.com": "news",
    "techcrunch.com": "news",
    "theverge.com": "news",
    "wired.com": "news",
    "arstechnica.com": "news",
    "engadget.com": "news",
    "cnet.com": "news",
    "zdnet.com": "news",
    "venturebeat.com": "news",
    "axios.com": "news",
    "politico.com": "news",
    "npr.org": "news",
    "time.com": "news",
    "newsweek.com": "news",
    "latimes.com": "news",
    "usatoday.com": "news",
    "nbcnews.com": "news",
    "cbsnews.com": "news",
    "foxnews.com": "news",
    "aljazeera.com": "news",
    "scmp.com": "news",
    "straitstimes.com": "news",
    "nikkei.com": "news",
    "japantimes.co.jp": "news",
    "asahi.com": "news",
    "yahoo.com": "news",
    "yahoo.co.jp": "news",
    "cnbc.com": "news",
    "vice.com": "news",
    "buzzfeed.com": "news",
    "vox.com": "news",
    "slate.com": "news",
    "atlantic.com": "news",
    "newyorker.com": "news",
    "scientificamerican.com": "science",
    "nationalgeographic.com": "news",
    "smithsonianmag.com": "news",
    "variety.com": "news",
    "hollywoodreporter.com": "news",
    "deadline.com": "news",
    "nhk.or.jp": "news",
    "chosun.com": "news",
    "joongang.co.kr": "news",
    "hankyung.com": "news",
    "channelnewsasia.com": "news",
    # ── education / 百科 / 慕课 / 教培 ────────────────────────────
    "wikipedia.org": "education",
    "wikimedia.org": "education",
    "britannica.com": "education",
    "khanacademy.org": "education",
    "archive.org": "education",
    "archive.is": "education",
    "archive.ph": "education",
    "wiktionary.org": "education",
    "wikidata.org": "education",
    "baike.com": "education",
    "hudong.com": "education",
    "mooc.cn": "education",
    "icourse163.org": "education",
    "xuetangx.com": "education",
    "zhihuishu.com": "education",
    "chaoxing.com": "education",
    "cnki.net": "education",
    "wanfangdata.com.cn": "education",
    "cqvip.com": "education",
    "cssn.cn": "education",
    "coursera.org": "education",
    "edx.org": "education",
    "udemy.com": "education",
    "udacity.com": "education",
    "skillshare.com": "education",
    "runoob.com": "education",
    "w3school.com.cn": "education",
    "liaoxuefeng.com": "education",
    "ruanyifeng.com": "education",
    "jikexueyuan.com": "education",
    "imooc.com": "education",
    "xueersi.com": "education",
    "zuoyebang.com": "education",
    "yuanfudao.com": "education",
    "vipkid.com.cn": "education",
    "koolearn.com": "education",
    "hujiang.com": "education",
    "shanbay.com": "education",
    "youdao.com": "education",
    "iciba.com": "education",
    "dict.cn": "education",
    # ── science / 学术 / 法律知识库 ───────────────────────────────
    "nature.com": "science",
    "science.org": "science",
    "sciencedirect.com": "science",
    "springer.com": "science",
    "wiley.com": "science",
    "nih.gov": "science",
    "arxiv.org": "science",
    "ieee.org": "science",
    "acm.org": "science",
    "researchgate.net": "science",
    "cnki.com.cn": "science",
    "cell.com": "science",
    "pnas.org": "science",
    "nejm.org": "science",
    "thelancet.com": "science",
    "bmj.com": "science",
    "jstor.org": "science",
    "ssrn.com": "science",
    "kaggle.com": "science",
    "huggingface.co": "science",
    "paperswithcode.com": "science",
    "openai.com": "science",
    "anthropic.com": "science",
    "python.org": "education",
    "nodejs.org": "education",
    "rust-lang.org": "education",
    "go.dev": "education",
    "golang.org": "education",
    "mozilla.org": "education",
    "w3.org": "education",
    "readthedocs.io": "education",
    "readthedocs.org": "education",
    "apache.org": "downloads",
    "gnu.org": "downloads",
    "kernel.org": "downloads",
    "linuxfoundation.org": "downloads",
    "cncf.io": "downloads",
    "debian.org": "downloads",
    "ubuntu.com": "downloads",
    "postgresql.org": "downloads",
    "mysql.com": "downloads",
    "mongodb.com": "downloads",
    "redis.io": "downloads",
    "elastic.co": "downloads",
    "pkulaw.com": "science",
    "lawtime.cn": "science",
    "66law.cn": "science",
    "chinacourt.org": "government",
    # ── shopping / 电商 / 本地生活 / 旅游 ─────────────────────────
    "taobao.com": "shopping",
    "tmall.com": "shopping",
    "jd.com": "shopping",
    "jd.hk": "shopping",
    "amazon.com": "shopping",
    "amazon.cn": "shopping",
    "amazon.co.uk": "shopping",
    "amazon.de": "shopping",
    "ebay.com": "shopping",
    "etsy.com": "shopping",
    "walmart.com": "shopping",
    "target.com": "shopping",
    "bestbuy.com": "shopping",
    "costco.com": "shopping",
    "ikea.com": "shopping",
    "nike.com": "shopping",
    "adidas.com": "shopping",
    "shopify.com": "shopping",
    "pinduoduo.com": "shopping",
    "yangkeduo.com": "shopping",
    "suning.com": "shopping",
    "vip.com": "shopping",
    "gome.com.cn": "shopping",
    "dangdang.com": "shopping",
    "kaola.com": "shopping",
    "smzdm.com": "shopping",
    "manmanbuy.com": "shopping",
    "aliexpress.com": "shopping",
    "1688.com": "shopping",
    "made-in-china.com": "shopping",
    "xiaomiyoupin.com": "shopping",
    "mi.com": "shopping",
    "xiaomi.com": "shopping",
    "huawei.com": "shopping",
    "honor.com": "shopping",
    "oppo.com": "shopping",
    "oppomobile.com": "shopping",
    "vivo.com": "shopping",
    "vivo.com.cn": "shopping",
    "meizu.com": "shopping",
    "lenovo.com.cn": "shopping",
    "apple.com.cn": "shopping",
    "apple.com": "shopping",
    "dewu.com": "shopping",
    "poizon.com": "shopping",
    "meituan.com": "shopping",
    "dianping.com": "shopping",
    "ele.me": "shopping",
    "eleme.com": "shopping",
    "koubei.com": "shopping",
    "ctrip.com": "shopping",
    "qunar.com": "shopping",
    "fliggy.com": "shopping",
    "ly.com": "shopping",
    "tuniu.com": "shopping",
    "mafengwo.cn": "shopping",
    "lvmama.com": "shopping",
    "amap.com": "shopping",
    "gaode.com": "shopping",
    "cainiao.com": "shopping",
    "sf-express.com": "shopping",
    "yto.net.cn": "shopping",
    "sto.cn": "shopping",
    "zto.com": "shopping",
    "yundaex.com": "shopping",
    "ems.com.cn": "shopping",
    "58.com": "shopping",
    "ganji.com": "shopping",
    "ke.com": "shopping",
    "lianjia.com": "shopping",
    "anjuke.com": "shopping",
    "fang.com": "shopping",
    "ziroom.com": "shopping",
    "airbnb.com": "shopping",
    "booking.com": "shopping",
    "expedia.com": "shopping",
    "tripadvisor.com": "shopping",
    "yelp.com": "shopping",
    "uber.com": "shopping",
    "lyft.com": "shopping",
    "doordash.com": "shopping",
    "craigslist.org": "shopping",
    "rakuten.co.jp": "shopping",
    "kayak.com": "shopping",
    "skyscanner.com": "shopping",
    "hotels.com": "shopping",
    "marriott.com": "shopping",
    "hilton.com": "shopping",
    # ── finance / 财经 / 支付 / 银行 ──────────────────────────────
    "eastmoney.com": "finance",
    "xueqiu.com": "finance",
    "wallstreetcn.com": "finance",
    "jin10.com": "finance",
    "10jqka.com.cn": "finance",
    "hexun.com": "finance",
    "cnstock.com": "finance",
    "cs.com.cn": "finance",
    "stcn.com": "finance",
    "jrj.com.cn": "finance",
    "cfi.cn": "finance",
    "cnfol.com": "finance",
    "futunn.com": "finance",
    "tigerbrokers.com": "finance",
    "bloomberg.com": "finance",
    "marketwatch.com": "finance",
    "investopedia.com": "finance",
    "morningstar.com": "finance",
    "seekingalpha.com": "finance",
    "coindesk.com": "finance",
    "coinbase.com": "finance",
    "binance.com": "finance",
    "paypal.com": "finance",
    "stripe.com": "finance",
    "visa.com": "finance",
    "mastercard.com": "finance",
    "chase.com": "finance",
    "bankofamerica.com": "finance",
    "wellsfargo.com": "finance",
    "barrons.com": "finance",
    "fool.com": "finance",
    "nerdwallet.com": "finance",
    "robinhood.com": "finance",
    "fidelity.com": "finance",
    "schwab.com": "finance",
    "vanguard.com": "finance",
    "blackrock.com": "finance",
    "alipay.com": "finance",
    "antgroup.com": "finance",
    "mybank.cn": "finance",
    "unionpay.com": "finance",
    "tenpay.com": "finance",
    "yeepay.com": "finance",
    "icbc.com.cn": "finance",
    "abchina.com": "finance",
    "boc.cn": "finance",
    "ccb.com": "finance",
    "bankcomm.com": "finance",
    "cmbchina.com": "finance",
    "spdb.com.cn": "finance",
    "cib.com.cn": "finance",
    "cmbc.com.cn": "finance",
    "citicbank.com": "finance",
    "pingan.com": "finance",
    "hsbc.com.cn": "finance",
    # ── search / 大厂入口（根域粗分）──────────────────────────────
    # *.gov / *.gov.cn 等由政府域名启发式覆盖，无需逐条 seed
    "google.com": "searchengines",
    "bing.com": "searchengines",
    "sogou.com": "searchengines",
    "baidu.com": "searchengines",  # 含百科等子域，根域统一按搜索
    "so.com": "searchengines",
    "sm.cn": "searchengines",
    "360.cn": "searchengines",
    "qihoo.com": "searchengines",
    "yandex.com": "searchengines",
    "duckduckgo.com": "searchengines",
    "tencent.com": "socialnet",
    "alibaba.com": "shopping",
    "alibaba.com.cn": "shopping",
    "bytedance.com": "socialnet",
    "netease.com": "news",
    # 国际组织 / 官方（非 .gov 启发式覆盖的）
    "un.org": "government",
    "worldbank.org": "government",
    "imf.org": "government",
    "oecd.org": "government",
    "europa.eu": "government",
    "nasa.gov": "science",
    "whitehouse.gov": "government",
    # ── webmail ───────────────────────────────────────────────────
    "gmail.com": "webmail",
    "outlook.com": "webmail",
    "126.com": "webmail",
    "yeah.net": "webmail",
    "foxmail.com": "webmail",
    # ── downloads / 开发托管 ──────────────────────────────────────
    "github.com": "downloads",
    "gitlab.com": "downloads",
    "bitbucket.org": "downloads",
    "npmjs.com": "downloads",
    "pypi.org": "downloads",
    "crates.io": "downloads",
    "rubygems.org": "downloads",
    "mvnrepository.com": "downloads",
    "docker.com": "downloads",
    "kubernetes.io": "downloads",
    "hashicorp.com": "downloads",
    "microsoft.com": "downloads",
    "notion.so": "downloads",
    "atlassian.com": "downloads",
    "slack.com": "downloads",
    "zoom.us": "downloads",
    "dropbox.com": "downloads",
    "box.com": "downloads",
    "figma.com": "hobby",
    "canva.com": "hobby",
    "dribbble.com": "hobby",
    "behance.net": "hobby",
    "cloudflare.com": "downloads",
    "digitalocean.com": "downloads",
    "heroku.com": "downloads",
    "vercel.com": "downloads",
    "netlify.com": "downloads",
    "salesforce.com": "downloads",
    "hubspot.com": "downloads",
    "zendesk.com": "downloads",
    "intercom.com": "downloads",
    "mailchimp.com": "downloads",
    "squarespace.com": "downloads",
    "wix.com": "downloads",
    "webflow.com": "downloads",
    "typeform.com": "downloads",
    "surveymonkey.com": "downloads",
    "tableau.com": "downloads",
    "snowflake.com": "downloads",
    "databricks.com": "downloads",
    "datadog.com": "downloads",
    "sentry.io": "downloads",
    "sourceforge.net": "downloads",
    "harmonyos.com": "downloads",
    "openharmony.cn": "downloads",
    # ── hospitals / health / 医疗电商 ─────────────────────────────
    "haodf.com": "hospitals",
    "dxy.cn": "hospitals",
    "familydoctor.cn": "hospitals",
    "120v.com.cn": "hospitals",
    "chunyuyisheng.com": "hospitals",
    "guahao.com": "hospitals",
    "weiyi.com": "hospitals",
    "xywy.com": "hospitals",
    "39.net": "hospitals",
    "120ask.com": "hospitals",
    "cmtopdr.com": "hospitals",
    "medsci.cn": "hospitals",
    "pumch.cn": "hospitals",
    "who.int": "hospitals",
    "cdc.gov": "hospitals",
    "fda.gov": "hospitals",
    "webmd.com": "hospitals",
    "mayoclinic.org": "hospitals",
    "healthline.com": "hospitals",
    "clevelandclinic.org": "hospitals",
    "hopkinsmedicine.org": "hospitals",
    "drugs.com": "hospitals",
    "rxlist.com": "hospitals",
    "alihealth.cn": "hospitals",
    "alijk.com": "hospitals",
    "jianke.com": "hospitals",
    "ykyao.com": "hospitals",
    "111.com.cn": "hospitals",
    # ── jobsearch / 招聘 ──────────────────────────────────────────
    "zhaopin.com": "jobsearch",
    "51job.com": "jobsearch",
    "liepin.com": "jobsearch",
    "lagou.com": "jobsearch",
    "zhipin.com": "jobsearch",
    "bosszhipin.com": "jobsearch",
    "maimai.cn": "jobsearch",
    "indeed.com": "jobsearch",
    "glassdoor.com": "jobsearch",
    "monster.com": "jobsearch",
    "lever.co": "jobsearch",
    "greenhouse.io": "jobsearch",
    "workday.com": "jobsearch",
    # ── automobile ────────────────────────────────────────────────
    "autohome.com.cn": "automobile",
    "pcauto.com.cn": "automobile",
    "bitauto.com": "automobile",
    "dongchedi.com": "automobile",
    "yiche.com": "automobile",
    "xcar.com.cn": "automobile",
    "cheshi.com": "automobile",
    # ── dating ────────────────────────────────────────────────────
    "jiayuan.com": "dating",
    "zhenai.com": "dating",
    "baihe.com": "dating",
    "tantanapp.com": "dating",
    "soulapp.cn": "dating",
    "momo.com": "dating",
    # ── isp / 运营商 / 天气 ───────────────────────────────────────
    "10086.cn": "isp",
    "chinamobile.com": "isp",
    "189.cn": "isp",
    "chinatelecom.com.cn": "isp",
    "10010.com": "isp",
    "chinaunicom.com": "isp",
    "weather.com.cn": "hobby",
    "tianqi.com": "hobby",
    "moji.com": "hobby",
    # ── url shorteners ────────────────────────────────────────────
    "bit.ly": "urlshortener",
    "t.co": "urlshortener",
    "tinyurl.com": "urlshortener",
    "shorturl.at": "urlshortener",
    "dwz.cn": "urlshortener",
    "url.cn": "urlshortener",
    "t.cn": "urlshortener",
    # ── image hosting ─────────────────────────────────────────────
    "imgur.com": "imagehosting",
    "flickr.com": "imagehosting",
    "qpic.cn": "imagehosting",
    "qlogo.cn": "imagehosting",
    "gtimg.cn": "imagehosting",
}


def _heuristic_domain_type(domain: str) -> str:
    """TLD / label heuristics when the curated map misses.

    Only match whole DNS labels (or known public-suffix shapes) to avoid
    false positives like ``mygovhelp.com`` / ``education.com``.
    """
    labels = [p for p in domain.split(".") if p]
    if len(labels) < 2:
        return ""
    tld = labels[-1]

    # 政府：*.gov / *.gov.cn / *.gov.uk；*.govt.nz；*.gob.*；*.gouv.fr；*.gc.ca；*.mil
    if "gov" in labels or "govt" in labels or "mil" in labels:
        return "government"
    if "gob" in labels or "gouv" in labels:
        return "government"
    if "gc" in labels and tld == "ca":
        return "government"
    if "go" in labels and tld in {"jp", "kr"}:
        return "government"
    # 国际组织 TLD（who.int / nato.int / …）
    if tld == "int":
        return "government"

    # 教育：*.edu…；*.ac.*；*.k12.*；英联邦中小学 *.sch.uk
    if "edu" in labels or "k12" in labels:
        return "education"
    if "ac" in labels and tld in {"cn", "uk", "jp", "kr"}:
        return "education"
    if "sch" in labels and tld == "uk":
        return "education"

    # 医疗：英国 NHS
    if "nhs" in labels:
        return "hospitals"

    # 医院/卫健：*.org.cn 且域名含常见关键词（弱启发）
    if domain.endswith(".org.cn") and any(
        k in domain
        for k in (
            "hospital",
            "hsp",
            "yiyuan",
            "health",
            "cdc",
            "clinic",
            "ylws",
            "yygh",
            "rmyy",
        )
    ):
        return "hospitals"
    return ""


def seed_domain_type(domain: str) -> str:
    """Return Shallalist code from seed map or light heuristics; else empty."""
    key = (domain or "").strip().lower()
    if not key:
        return ""
    if key in DOMAIN_TYPE_SEEDS:
        return DOMAIN_TYPE_SEEDS[key]
    parts = key.split(".")
    for i in range(1, len(parts) - 1):
        candidate = ".".join(parts[i:])
        if candidate in DOMAIN_TYPE_SEEDS:
            return DOMAIN_TYPE_SEEDS[candidate]
    return _heuristic_domain_type(key)
