"""Domain type rules from homepage SEO / JSON-LD signals (no LLM)."""

from __future__ import annotations

from aperix_geo.services.crawl.seo import SeoMetadata
from aperix_geo.services.domain.taxonomy import DOMAIN_TYPES, normalize_domain_type

# High-confidence schema.org @type → Shallalist code
_SCHEMA_TYPE_MAP: dict[str, str] = {
    # news / media
    "NewsMediaOrganization": "news",
    "NewsArticle": "news",
    "ReportageNewsArticle": "news",
    "AnalysisNewsArticle": "news",
    "OpinionNewsArticle": "news",
    "BackgroundNewsArticle": "news",
    "LiveBlogPosting": "news",
    # government / politics
    "GovernmentOrganization": "government",
    "GovernmentOffice": "government",
    "GovernmentService": "government",
    "LegislativeBuilding": "government",
    "CourtHouse": "government",
    # education
    "CollegeOrUniversity": "education",
    "EducationalOrganization": "education",
    "School": "education",
    "HighSchool": "education",
    "ElementarySchool": "education",
    "MiddleSchool": "education",
    "Preschool": "education",
    "Course": "education",
    "CourseInstance": "education",
    "LearningResource": "education",
    # medical / health
    "Hospital": "hospitals",
    "MedicalOrganization": "hospitals",
    "Physician": "hospitals",
    "MedicalClinic": "hospitals",
    "Pharmacy": "hospitals",
    "Dentist": "hospitals",
    "VeterinaryCare": "hospitals",
    "MedicalProcedure": "hospitals",
    "Drug": "drugs",
    "DietarySupplement": "drugs",
    # shopping / commerce（避免 Product / ItemList 等过宽类型）
    "OnlineStore": "shopping",
    "Store": "shopping",
    "ShoppingCenter": "shopping",
    "DepartmentStore": "shopping",
    "ClothingStore": "shopping",
    "ElectronicsStore": "shopping",
    "FurnitureStore": "shopping",
    "GroceryStore": "shopping",
    "HardwareStore": "shopping",
    "HomeGoodsStore": "shopping",
    "JewelryStore": "shopping",
    "SportingGoodsStore": "shopping",
    "BookStore": "shopping",
    "Florist": "shopping",
    # jobs
    "JobPosting": "jobsearch",
    "EmploymentAgency": "jobsearch",
    # finance
    "FinancialService": "finance",
    "BankOrCreditUnion": "finance",
    "InvestmentOrDeposit": "finance",
    "InsuranceAgency": "finance",
    "AccountingService": "finance",
    "ATMOrCashMachine": "finance",
    "BrokerageAccount": "finance",
    "PaymentService": "finance",
    "LoanOrCredit": "finance",
    # automobile
    "AutoDealer": "automobile",
    "AutoRepair": "automobile",
    "AutoBodyShop": "automobile",
    "AutoPartsStore": "automobile",
    "AutoRental": "automobile",
    "AutoWash": "automobile",
    "GasStation": "automobile",
    "Vehicle": "automobile",
    "Car": "automobile",
    "Motorcycle": "automobile",
    # broadcast / radio / tv
    "RadioStation": "radiotv",
    "RadioSeries": "radiotv",
    "RadioEpisode": "radiotv",
    "TVStation": "radiotv",
    "TVSeries": "radiotv",
    "TVEpisode": "radiotv",
    "TVSeason": "radiotv",
    "BroadcastService": "radiotv",
    "BroadcastEvent": "radiotv",
    "BroadcastChannel": "radiotv",
    # music
    "MusicGroup": "music",
    "MusicAlbum": "music",
    "MusicRecording": "music",
    "MusicPlaylist": "music",
    "MusicComposition": "music",
    "MusicVenue": "music",
    "MusicEvent": "music",
    # movies / games
    "MovieTheater": "movies",
    "Movie": "movies",
    "VideoObject": "movies",
    "VideoGame": "recreation",
    "VideoGameSeries": "recreation",
    # search / software / downloads
    "SearchAction": "searchengines",
    "WebApplication": "downloads",
    "SoftwareApplication": "downloads",
    "MobileApplication": "downloads",
    "ComputerApplication": "downloads",
    # images
    "ImageGallery": "imagehosting",
    "ImageObject": "imagehosting",
    "Photograph": "imagehosting",
    # social / discussion
    "DiscussionForumPosting": "forum",
    "SocialMediaPosting": "socialnet",
    "ProfilePage": "socialnet",
    # science / research
    "ScholarlyArticle": "science",
    "Dataset": "science",
    "ResearchProject": "science",
    "TechArticle": "science",
    "APIReference": "science",
    "SoftwareSourceCode": "science",
    # recreation / travel / food / sports
    "TouristAttraction": "recreation",
    "TouristDestination": "recreation",
    "TravelAgency": "recreation",
    "LodgingBusiness": "recreation",
    "Hotel": "recreation",
    "Resort": "recreation",
    "Campground": "recreation",
    "AmusementPark": "recreation",
    "Museum": "recreation",
    "Zoo": "recreation",
    "Aquarium": "recreation",
    "StadiumOrArena": "recreation",
    "SportsClub": "recreation",
    "SportsEvent": "recreation",
    "SportsTeam": "recreation",
    "ExerciseGym": "recreation",
    "Restaurant": "recreation",
    "CafeOrCoffeeShop": "recreation",
    "BarOrPub": "recreation",
    "FoodEstablishment": "recreation",
    "Recipe": "recreation",
    # dating
    "DatingService": "dating",
    # religion
    "PlaceOfWorship": "religion",
    "Church": "religion",
    "Mosque": "religion",
    "Synagogue": "religion",
    "HinduTemple": "religion",
    "BuddhistTemple": "religion",
    # alcohol
    "Winery": "alcohol",
    "Brewery": "alcohol",
    "Distillery": "alcohol",
    "LiquorStore": "alcohol",
    # email / isp
    "EmailMessage": "webmail",
    "ISP": "isp",
    # fashion / models
    "BeautySalon": "models",
    "HairSalon": "models",
    "NailSalon": "models",
    "DaySpa": "models",
}

# Phrase → type; matched longest-first against title/description/keywords blob.
# Prefer multi-char / multi-word phrases to limit false positives.
_KEYWORD_RULES: tuple[tuple[str, str], ...] = (
    # —— jobsearch ——
    ("求职招聘", "jobsearch"),
    ("招聘求职", "jobsearch"),
    ("人才招聘", "jobsearch"),
    ("校园招聘", "jobsearch"),
    ("社会招聘", "jobsearch"),
    ("找工作", "jobsearch"),
    ("招人", "jobsearch"),
    ("猎头", "jobsearch"),
    ("职位搜索", "jobsearch"),
    ("投递简历", "jobsearch"),
    ("在线简历", "jobsearch"),
    ("职位列表", "jobsearch"),
    ("招聘会", "jobsearch"),
    ("用人单位", "jobsearch"),
    ("job search", "jobsearch"),
    ("job board", "jobsearch"),
    ("careers", "jobsearch"),
    ("recruiting", "jobsearch"),
    ("recruitment", "jobsearch"),
    ("resume", "jobsearch"),
    ("招聘", "jobsearch"),
    ("求职", "jobsearch"),
    ("简历", "jobsearch"),
    ("职位", "jobsearch"),
    ("面试", "jobsearch"),
    # —— forum ——
    ("论坛社区", "forum"),
    ("社区论坛", "forum"),
    ("贴吧", "forum"),
    ("讨论区", "forum"),
    ("留言板", "forum"),
    ("版主", "forum"),
    ("回帖", "forum"),
    ("发帖", "forum"),
    ("帖子", "forum"),
    ("bbs", "forum"),
    ("discussion forum", "forum"),
    ("message board", "forum"),
    ("论坛", "forum"),
    # —— socialnet ——
    ("社交网络", "socialnet"),
    ("社交媒体", "socialnet"),
    ("社交平台", "socialnet"),
    ("短视频", "socialnet"),
    ("直播平台", "socialnet"),
    ("粉丝互动", "socialnet"),
    ("微博", "socialnet"),
    ("朋友圈", "socialnet"),
    ("social network", "socialnet"),
    ("social media", "socialnet"),
    ("social platform", "socialnet"),
    # —— news ——
    ("新闻资讯", "news"),
    ("资讯门户", "news"),
    ("热点资讯", "news"),
    ("时事新闻", "news"),
    ("财经新闻", "news"),
    ("科技新闻", "news"),
    ("新闻媒体", "news"),
    ("深度报道", "news"),
    ("报社", "news"),
    ("通讯社", "news"),
    ("记者", "news"),
    ("编辑部", "news"),
    ("头条", "news"),
    ("晚报", "news"),
    ("早报", "news"),
    ("周刊", "news"),
    ("时报", "news"),
    ("日报", "news"),
    ("newspaper", "news"),
    ("news media", "news"),
    ("breaking news", "news"),
    ("journalist", "news"),
    ("新闻", "news"),
    ("资讯", "news"),
    # —— shopping ——
    ("网上购物", "shopping"),
    ("网上商城", "shopping"),
    ("电子商务", "shopping"),
    ("电商平台", "shopping"),
    ("跨境电商", "shopping"),
    ("在线购物", "shopping"),
    ("官方商城", "shopping"),
    ("旗舰店", "shopping"),
    ("优惠券", "shopping"),
    ("加入购物车", "shopping"),
    ("立即购买", "shopping"),
    ("秒杀", "shopping"),
    ("买家", "shopping"),
    ("卖家", "shopping"),
    ("下单", "shopping"),
    ("快递", "shopping"),
    ("物流", "shopping"),
    ("包邮", "shopping"),
    ("退换货", "shopping"),
    ("电商", "shopping"),
    ("购物", "shopping"),
    ("商城", "shopping"),
    ("网店", "shopping"),
    ("e-commerce", "shopping"),
    ("ecommerce", "shopping"),
    ("online store", "shopping"),
    ("online shop", "shopping"),
    ("shopping", "shopping"),
    # —— finance ——
    ("金融理财", "finance"),
    ("理财产品", "finance"),
    ("股票行情", "finance"),
    ("证券交易", "finance"),
    ("基金理财", "finance"),
    ("保险服务", "finance"),
    ("网上银行", "finance"),
    ("手机银行", "finance"),
    ("支付平台", "finance"),
    ("数字货币", "finance"),
    ("加密货币", "finance"),
    ("信用卡", "finance"),
    ("开户", "finance"),
    ("券商", "finance"),
    ("股民", "finance"),
    ("股市", "finance"),
    ("cryptocurrency", "finance"),
    ("stock market", "finance"),
    ("investment", "finance"),
    ("banking", "finance"),
    ("broker", "finance"),
    ("证券", "finance"),
    ("银行", "finance"),
    ("理财", "finance"),
    ("基金", "finance"),
    ("保险", "finance"),
    ("期货", "finance"),
    ("外汇", "finance"),
    ("贷款", "finance"),
    # —— hospitals / drugs ——
    ("医疗健康", "hospitals"),
    ("互联网医院", "hospitals"),
    ("在线问诊", "hospitals"),
    ("健康咨询", "hospitals"),
    ("预约挂号", "hospitals"),
    ("电子病历", "hospitals"),
    ("专家门诊", "hospitals"),
    ("门诊", "hospitals"),
    ("住院", "hospitals"),
    ("患者", "hospitals"),
    ("护士", "hospitals"),
    ("牙医", "hospitals"),
    ("中医", "hospitals"),
    ("西医", "hospitals"),
    ("telehealth", "hospitals"),
    ("telemedicine", "hospitals"),
    ("healthcare", "hospitals"),
    ("hospital", "hospitals"),
    ("clinic", "hospitals"),
    ("physician", "hospitals"),
    ("doctor", "hospitals"),
    ("nurse", "hospitals"),
    ("patient", "hospitals"),
    ("医院", "hospitals"),
    ("诊所", "hospitals"),
    ("问诊", "hospitals"),
    ("挂号", "hospitals"),
    ("医生", "hospitals"),
    ("医师", "hospitals"),
    ("名医", "hospitals"),
    ("药店", "drugs"),
    ("药房", "drugs"),
    ("药品", "drugs"),
    ("处方药", "drugs"),
    ("pharmacy", "drugs"),
    # —— government / politics ——
    ("政府官网", "government"),
    ("政务服务", "government"),
    ("政务公开", "government"),
    ("办事大厅", "government"),
    ("一网通办", "government"),
    ("市民服务", "government"),
    ("市政府", "government"),
    ("省政府", "government"),
    ("国务院", "government"),
    ("gov.cn", "government"),
    ("政府", "government"),
    ("政务", "government"),
    ("公示", "government"),
    ("人大", "politics"),
    ("政协", "politics"),
    ("党务", "politics"),
    ("政治", "politics"),
    ("government", "government"),
    # —— education ——
    ("在线教育", "education"),
    ("网络教育", "education"),
    ("职业教育", "education"),
    ("高等教育", "education"),
    ("中小学", "education"),
    ("慕课", "education"),
    ("公开课", "education"),
    ("网课", "education"),
    ("考研", "education"),
    ("高考", "education"),
    ("教师", "education"),
    ("老师", "education"),
    ("教授", "education"),
    ("讲师", "education"),
    ("学员", "education"),
    ("校园", "education"),
    ("大学", "education"),
    ("学院", "education"),
    ("学校", "education"),
    ("培训", "education"),
    ("课件", "education"),
    ("university", "education"),
    ("online course", "education"),
    ("e-learning", "education"),
    ("elearning", "education"),
    ("teacher", "education"),
    ("professor", "education"),
    # —— automobile ——
    ("汽车之家", "automobile"),
    ("新车报价", "automobile"),
    ("二手车", "automobile"),
    ("汽车论坛", "automobile"),
    ("车型库", "automobile"),
    ("4s店", "automobile"),
    ("4s 店", "automobile"),
    ("试驾", "automobile"),
    ("汽车保养", "automobile"),
    ("车主", "automobile"),
    ("车市", "automobile"),
    ("汽车", "automobile"),
    ("车友", "automobile"),
    ("used cars", "automobile"),
    ("auto dealer", "automobile"),
    ("automotive", "automobile"),
    # —— gamble ——
    ("网络博彩", "gamble"),
    ("在线赌场", "gamble"),
    ("体育竞猜", "gamble"),
    ("博彩", "gamble"),
    ("彩票", "gamble"),
    ("赌场", "gamble"),
    ("online casino", "gamble"),
    ("sports betting", "gamble"),
    # —— searchengines ——
    ("搜索引擎", "searchengines"),
    ("网页搜索", "searchengines"),
    ("全网搜索", "searchengines"),
    ("search engine", "searchengines"),
    ("web search", "searchengines"),
    # —— science / tech ——
    ("开源社区", "science"),
    ("技术文档", "science"),
    ("开发者", "science"),
    ("工程师", "science"),
    ("研究员", "science"),
    ("api 文档", "science"),
    ("api文档", "science"),
    ("学术论文", "science"),
    ("科研", "science"),
    ("实验室", "science"),
    ("论文", "science"),
    ("developer docs", "science"),
    ("documentation", "science"),
    ("open source", "science"),
    ("research", "science"),
    ("engineer", "science"),
    ("arxiv", "science"),
    # —— downloads / software ——
    ("软件下载", "downloads"),
    ("应用下载", "downloads"),
    ("客户端下载", "downloads"),
    ("安装包", "downloads"),
    ("app store", "downloads"),
    ("software download", "downloads"),
    ("免费下载", "downloads"),
    ("下载中心", "downloads"),
    # —— movies / music / radiotv / webradio ——
    ("在线影视", "movies"),
    ("电影票", "movies"),
    ("电视剧", "movies"),
    ("视频网站", "movies"),
    ("流媒体", "movies"),
    ("影院", "movies"),
    ("演员", "movies"),
    ("streaming", "movies"),
    ("movie", "movies"),
    ("在线音乐", "music"),
    ("音乐播放", "music"),
    ("歌单", "music"),
    ("歌手", "music"),
    ("专辑", "music"),
    ("music streaming", "music"),
    ("广播电视", "radiotv"),
    ("电视台", "radiotv"),
    ("广播电台", "radiotv"),
    ("主持人", "radiotv"),
    ("网络电台", "webradio"),
    ("internet radio", "webradio"),
    ("webradio", "webradio"),
    # —— recreation / hobby ——
    ("旅游攻略", "recreation"),
    ("酒店预订", "recreation"),
    ("景点门票", "recreation"),
    ("休闲娱乐", "recreation"),
    ("游戏社区", "recreation"),
    ("手游", "recreation"),
    ("电竞", "recreation"),
    ("玩家", "recreation"),
    ("游客", "recreation"),
    ("旅游", "recreation"),
    ("旅行", "recreation"),
    ("度假", "recreation"),
    ("美食", "recreation"),
    ("菜谱", "recreation"),
    ("travel", "recreation"),
    ("tourism", "recreation"),
    ("gaming", "recreation"),
    ("兴趣爱好", "hobby"),
    ("手工", "hobby"),
    ("hobby", "hobby"),
    # —— dating ——
    ("婚恋交友", "dating"),
    ("相亲交友", "dating"),
    ("在线相亲", "dating"),
    ("征婚", "dating"),
    ("单身", "dating"),
    ("脱单", "dating"),
    ("dating", "dating"),
    ("交友", "dating"),
    # —— religion / fortunetelling ——
    ("宗教信仰", "religion"),
    ("佛教", "religion"),
    ("基督教", "religion"),
    ("伊斯兰教", "religion"),
    ("教堂", "religion"),
    ("寺庙", "religion"),
    ("religion", "religion"),
    ("占卜运势", "fortunetelling"),
    ("星座运势", "fortunetelling"),
    ("算命", "fortunetelling"),
    ("占卜", "fortunetelling"),
    ("horoscope", "fortunetelling"),
    # —— alcohol ——
    ("葡萄酒", "alcohol"),
    ("白酒", "alcohol"),
    ("啤酒", "alcohol"),
    ("酒类", "alcohol"),
    ("酒庄", "alcohol"),
    ("winery", "alcohol"),
    ("brewery", "alcohol"),
    # —— models / fashion ——
    ("时尚潮流", "models"),
    ("模特", "models"),
    ("美妆", "models"),
    ("时装", "models"),
    ("穿搭", "models"),
    ("fashion", "models"),
    ("beauty", "models"),
    # —— webmail / isp / urlshortener / imagehosting / adv / tracker ——
    ("网页邮箱", "webmail"),
    ("电子邮箱", "webmail"),
    ("webmail", "webmail"),
    ("电子邮件", "webmail"),
    ("收件箱", "webmail"),
    ("互联网接入", "isp"),
    ("宽带运营商", "isp"),
    ("internet service provider", "isp"),
    ("短链接", "urlshortener"),
    ("短网址", "urlshortener"),
    ("url shortener", "urlshortener"),
    ("link shortener", "urlshortener"),
    ("图床", "imagehosting"),
    ("图片托管", "imagehosting"),
    ("image hosting", "imagehosting"),
    ("广告联盟", "adv"),
    ("广告投放", "adv"),
    ("advertising network", "adv"),
    ("ad network", "adv"),
    ("数据分析平台", "tracker"),
    ("网站统计", "tracker"),
    ("analytics", "tracker"),
    # —— adult / weapons / spyware / warez（低优先级长词，减少误伤）——
    ("成人内容", "porn"),
    ("成人网站", "porn"),
    ("adult content", "porn"),
    ("两性健康", "sex"),
    ("性爱", "sex"),
    ("武器装备", "weapons"),
    ("枪支", "weapons"),
    ("weapons", "weapons"),
    ("恶意软件", "spyware"),
    ("spyware", "spyware"),
    ("malware", "spyware"),
    ("盗版资源", "warez"),
    ("破解版", "warez"),
    ("warez", "warez"),
    ("redirect", "redirector"),
    ("url redirect", "redirector"),
)


def _blob(meta: SeoMetadata) -> str:
    parts = [
        meta.title or "",
        meta.description or "",
        meta.site_name or "",
        meta.publisher or "",
        meta.content_type or "",
        " ".join(meta.keywords or ()),
        " ".join(meta.categories or ()),
        " ".join(meta.brand_names or ()),
        " ".join(meta.speakable_text or ()),
    ]
    return " ".join(parts).lower()


def _from_schema(meta: SeoMetadata) -> str:
    for raw in meta.schema_types or ():
        key = (raw or "").strip().split("/")[-1]
        mapped = _SCHEMA_TYPE_MAP.get(key)
        if mapped and mapped in DOMAIN_TYPES:
            return mapped
    return ""


def _from_keywords(meta: SeoMetadata) -> str:
    text = _blob(meta)
    if not text.strip():
        return ""
    for phrase, code in sorted(_KEYWORD_RULES, key=lambda item: len(item[0]), reverse=True):
        if phrase.lower() in text and code in DOMAIN_TYPES:
            return code
    return ""


def domain_type_from_homepage_seo(domain: str, meta: SeoMetadata | None) -> str:
    """Return Shallalist code from homepage SEO, or empty if uncertain.

    ``domain`` is reserved for future host-specific tweaks; unused for now.
    """
    _ = domain
    if meta is None:
        return ""
    for candidate in (_from_schema(meta), _from_keywords(meta)):
        if not candidate:
            continue
        normalized = normalize_domain_type(candidate)
        if normalized != "other":
            return normalized
    return ""
