import type { InvalidateQueryFilters, QueryClient } from "@tanstack/react-query";

export const queryKeys = {
  subjects: ["subjects"] as const,
  me: ["auth", "me"] as const,
  overview: (subjectId: string, from: string, to: string) =>
    ["overview", subjectId, from, to] as const,
  rank: (subjectId: string, from: string, to: string) =>
    ["rank", subjectId, from, to] as const,
  analysisEntities: (subjectId: string) => ["analysis-entities", subjectId] as const,
  analysisOverview: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-overview", subjectId, entityId, platformKey, topicKey, from, to] as const,
  dashboardOverview: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["dashboard-overview", subjectId, entityId, platformKey, topicKey, from, to] as const,
  analysisRank: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-rank", subjectId, entityId, platformKey, topicKey, from, to] as const,
  visibilityAnalysis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-visibility", subjectId, entityId, platformKey, topicKey, from, to] as const,
  analysisPrompts: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    search: string,
    listTopicId: string,
    sortBy: string,
    order: string,
  ) =>
    [
      "analysis-prompts",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      page,
      pageSize,
      search,
      listTopicId,
      sortBy,
      order,
    ] as const,
  analysisTopics: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-topics", subjectId, entityId, platformKey, topicKey, from, to] as const,
  analysisPlatforms: (subjectId: string, from: string, to: string) =>
    ["analysis-platforms", subjectId, from, to] as const,
  platformAnalysis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    matrixRow: string,
  ) =>
    ["analysis-platform", subjectId, entityId, platformKey, topicKey, from, to, matrixRow] as const,
  citationAnalysis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-citation", subjectId, entityId, platformKey, topicKey, from, to] as const,
  citationDomains: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
    search: string,
  ) =>
    [
      "analysis-citation-domains",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      page,
      pageSize,
      sortBy,
      order,
      search,
    ] as const,
  citationUrls: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
    search: string,
  ) =>
    [
      "analysis-citation-urls",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      page,
      pageSize,
      sortBy,
      order,
      search,
    ] as const,
  citationDomainAnalysis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    domain: string,
    from: string,
    to: string,
  ) =>
    ["analysis-citation-domain", subjectId, entityId, platformKey, topicKey, domain, from, to] as const,
  citationDomainUrls: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    domain: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "analysis-citation-domain-urls",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      domain,
      from,
      to,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  citationDomainPrompts: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    domain: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "analysis-citation-domain-prompts",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      domain,
      from,
      to,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  sentimentAnalysis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["analysis-sentiment", subjectId, entityId, platformKey, topicKey, from, to] as const,
  analysisResponses: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    sentimentLabel: string | null,
    promptId?: string,
    page?: number,
    pageSize?: number,
    sortBy?: string | null,
    order?: string,
  ) =>
    [
      "analysis-responses",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      sentimentLabel ?? "all",
      promptId ?? "",
      page ?? 1,
      pageSize ?? 10,
      sortBy ?? "created_at",
      order ?? "desc",
    ] as const,
  diagnosisContentSummary: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) =>
    ["diagnosis-content-summary", subjectId, entityId, platformKey, topicKey, from, to] as const,
  diagnosisContent: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "diagnosis-content",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  diagnosisContentDetail: (
    subjectId: string,
    promptId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) =>
    [
      "diagnosis-content-detail",
      subjectId,
      promptId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
    ] as const,
  contentOpportunities: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    search: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "content-opportunity",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      search,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  contentOpportunityDetail: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    promptId: string,
  ) =>
    [
      "content-opportunity-detail",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      promptId,
    ] as const,
  backlinkOpportunities: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    search: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "backlink-opportunity",
      subjectId,
      entityId,
      platformKey,
      topicKey,
      from,
      to,
      search,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  brandOpportunities: (
    subjectId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    search: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "brand-opportunity",
      subjectId,
      platformKey,
      topicKey,
      from,
      to,
      search,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  backlinkOpportunityDetail: (
    subjectId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    domain: string,
  ) =>
    [
      "backlink-opportunity-detail",
      subjectId,
      platformKey,
      topicKey,
      from,
      to,
      domain,
    ] as const,
  backlinkOpportunityUrls: (
    subjectId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    domain: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "backlink-opportunity-urls",
      subjectId,
      platformKey,
      topicKey,
      from,
      to,
      domain,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  backlinkOpportunityPrompts: (
    subjectId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
    domain: string,
    page: number,
    pageSize: number,
    sortBy: string,
    order: string,
  ) =>
    [
      "backlink-opportunity-prompts",
      subjectId,
      platformKey,
      topicKey,
      from,
      to,
      domain,
      page,
      pageSize,
      sortBy,
      order,
    ] as const,
  diagnosis: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    from: string,
    to: string,
  ) => ["diagnosis", subjectId, entityId, platformKey, topicKey, from, to] as const,
  samplingJob: (jobId: string) => ["sampling-job", jobId] as const,
  samplingPlatforms: ["sampling", "platforms"] as const,
  subjectCompetitors: (subjectId: string) => ["subject-competitors", subjectId] as const,
  subjectPrompts: (subjectId: string) => ["subject-prompts", subjectId] as const,
  subjectTopics: (subjectId: string) => ["subject-topics", subjectId] as const,
  promptDetail: (
    subjectId: string,
    entityId: string,
    platformKey: string,
    topicKey: string,
    promptId: string,
    from: string,
    to: string,
  ) => ["prompt-detail", subjectId, entityId, platformKey, topicKey, promptId, from, to] as const,
  llmResponse: (responseId: string) => ["llm-response", responseId] as const,
};

/**
 * 目录类接口（entities / topics / competitors / sampling/platforms）：
 * 同 tab 会话内只请求一次；刷新页面清缓存；切换 subject 靠 queryKey 区分各拉一次。
 */
export const sessionCatalogQueryOptions = {
  staleTime: Infinity,
  gcTime: Infinity,
} as const;

/** Mark matching React Query cache entries stale. */
export function clearQueries(queryClient: QueryClient, filters: InvalidateQueryFilters) {
  void queryClient.invalidateQueries(filters);
}

export function clearAnalysisCatalog(queryClient: QueryClient, subjectId: string) {
  clearQueries(queryClient, { queryKey: queryKeys.analysisEntities(subjectId) });
  clearQueries(queryClient, { queryKey: queryKeys.subjectTopics(subjectId) });
  clearQueries(queryClient, { queryKey: queryKeys.subjectCompetitors(subjectId) });
}

export function clearSamplingPlatformCatalog(queryClient: QueryClient) {
  clearQueries(queryClient, { queryKey: queryKeys.samplingPlatforms });
}
