export const queryKeys = {
  subjects: ["subjects"] as const,
  me: ["auth", "me"] as const,
  overview: (subjectId: string, from: string, to: string) =>
    ["overview", subjectId, from, to] as const,
  rank: (subjectId: string, from: string, to: string) =>
    ["rank", subjectId, from, to] as const,
  analysisOverview: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["analysis-overview", subjectId, from, to, topicId, platformId] as const,
  analysisRank: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["analysis-rank", subjectId, from, to, topicId, platformId] as const,
  visibilityAnalysis: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["visibility-analysis", subjectId, from, to, topicId, platformId] as const,
  analysisPrompts: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["analysis-prompts", subjectId, from, to, topicId, platformId] as const,
  analysisTopics: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["analysis-topics", subjectId, from, to, topicId, platformId] as const,
  analysisPlatforms: (subjectId: string, from: string, to: string) =>
    ["analysis-platforms", subjectId, from, to] as const,
  platformMatrix: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["platform-matrix", subjectId, from, to, topicId, platformId] as const,
  analysisCitationRank: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["analysis-citation-rank", subjectId, from, to, topicId, platformId] as const,
  citationAnalysis: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["citation-analysis", subjectId, from, to, topicId, platformId] as const,
  citationDomainAnalysis: (
    subjectId: string,
    host: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["citation-domain-analysis", subjectId, host, from, to, topicId, platformId] as const,
  analysisDailySentiment: (subjectId: string, from: string, to: string) =>
    ["analysis-daily-sentiment", subjectId, from, to] as const,
  sentimentAnalysis: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["sentiment-analysis", subjectId, from, to, topicId, platformId] as const,
  contentOpportunities: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["content-opportunities", subjectId, from, to, topicId, platformId] as const,
  backlinkOpportunities: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["backlink-opportunities", subjectId, from, to, topicId, platformId] as const,
  diagnosis: (
    subjectId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["diagnosis", subjectId, from, to, topicId, platformId] as const,
  pipelineStatus: (subjectId: string) => ["pipeline-status", subjectId] as const,
  samplingJob: (jobId: string) => ["sampling-job", jobId] as const,
  samplingPlatforms: ["sampling-platforms"] as const,
  brandCompetitors: (subjectId: string) => ["brand-competitors", subjectId] as const,
  brandPrompts: (subjectId: string) => ["brand-prompts", subjectId] as const,
  subjectTopics: (subjectId: string) => ["subject-topics", subjectId] as const,
  promptDetailVisibility: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-visibility", subjectId, promptId, from, to, topicId, platformId] as const,
  promptDetailCitation: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-citation", subjectId, promptId, from, to, topicId, platformId] as const,
  promptDetailPlatforms: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-platforms", subjectId, promptId, from, to, topicId, platformId] as const,
  promptDetailPrompts: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-prompts", subjectId, promptId, from, to, topicId, platformId] as const,
  promptDetailOpportunities: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-opportunities", subjectId, promptId, from, to, topicId, platformId] as const,
  promptDetailResponses: (
    subjectId: string,
    promptId: string,
    from: string,
    to: string,
    topicId = "all",
    platformId = "all",
  ) => ["prompt-detail-responses", subjectId, promptId, from, to, topicId, platformId] as const,
  llmResponse: (responseId: string) => ["llm-response", responseId] as const,
};
